name: LEMP Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Docker Compose (v2)
        run: |
          sudo apt update
          sudo apt install docker-compose

      - name: Build Docker images
        run: docker compose build   

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: docker compose push    # ✅ no hyphen
